[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "newsapi>=0.1.1",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "twilio>=9.6.1",
    "yfinance>=0.2.61",
]
